//
//  Constants.cpp
//  Stock-Broker-v2
//
//  Created by Matt Wood on 7/2/17.
//  Copyright © 2017 MattWood. All rights reserved.
//

#include "Constants.hpp"

const bool Constants::logTicks = false;
const bool Constants::logCandles = false;
const bool Constants::logBuySell = false;
const bool Constants::logProfits = true;
const bool Constants::logResponse = false;

const bool Constants::clearOrderAtDayEnd = false;

const std::string Constants::readDirectory = "/media/matt/Seagate Expansion Drive";
const std::string Constants::writeDirectory = "/media/matt/Seagate\\ Expansion\\ Drive";

const std::string Constants::stocksForQuotesAsCsv = "BHGE,APRN,ATUS,CARS,UPL,DXC,SNAP,FTI,CLNS,CNDT,PK,UWT,DWT,ARNC,AA,SD,ZTO,YUMC,NTNX,JCI,TWLO,HTZ,UA,AVGO,SQ,HPE,FDC,NLSN,AGI,KHC,PYPL,CC,FIT,MNST,LABU,LABD,MOMO,LC,CRC,UBS,ZAYO,FCAU,FMSA,PLD,EQR,NRZ,BRX,OHI,AGNC,CUZ,GGP,CBL,VER,DDR,MFA,WPG,HCP,WY,AMT,NLY,AMH,CCI,VTR,STWD,HST,TWO,DRE,KIM,SHO,MPW,CXW,DRH,SRC,CFG,BABA,AUPH,MBLY,SYF,PBR.A,NVS,BX,VALE,JD,ETP,CTRP,INFY,PBR,BTI,SAN,NOK,RDS.B,BHP,BBVA,VIPS,SID,BIDU,RIO,FIG,SBGL,CS,CX,BBL,AMRN,ITUB,GSK,BP,TEVA,AU,IBN,TSM,LYG,EPD,GGB,ETE,RDS.A,PAA,KKR,ERIC,CIG,VOD,HIMX,BBD,HSBC,AZN,MLCO,STO,SFUN,BCS,BSBR,GPRO,INFO,PE,WIN,LULU,GLUU,T,HRB,MTG,ASNA,CDE,PAAS,DVN,EFA,GPS,THC,VXX,GPK,TECK,JPM,CYTR,SAND,KR,KO,NVDA,FTNT,ADBE,NUAN,CBS,CBI,CBG,P,UAL,NKE,TNA,WMB,KRE,TAHO,ANF,NUGT,PHM,IAU,IAG,BA,IMMU,ALXN,ARRY,UCO,TSLA,VTI,TLT,GRPN,TBT,TXMD,GIS,DXJ,INDA,PFF,PFE,CNX,CNQ,CNP,XLV,MXIM,LEN,RDN,RDC,ODP,TRQ,IP,URBN,FNSR,WBA,C,TMUS,EQT,NRG,GME,INFN,CLR,MRVL,PDS,CLF,CLDX,ENB,HRL,WETF,AMGN,ESV,HL,ADI,ADM,ADP,SQQQ,TJX,PBI,AABA,PBF,MNK,HD,STLD,D,HPQ,AMAT,WEN,AAPL,SPWR,WYNN,BTG,BTE,TGNA,DBC,CHS,CHK,FXI,DBEF,OIL,VLO,GM,GE,GG,GS,GT,XBI,VIAV,FAST,VRX,MDLZ,EWU,EWW,EWY,EWZ,EWG,EWA,EWC,EWH,EWJ,KMX,QID,SWFT,JCP,EXAS,OCLR,OLN,S,GLD,TZA,ISBC,SKX,CSX,ROST,LPI,TRGP,ABX,ABT,ABC,DFS,DGAZ,MDR,MSFT,FL,SMH,FB,FTR,TXN,EBAY,LRCX,MYL,LVS,ARCC,HES,QEP,DDD,COTY,MFC,BRCD,EXEL,IWM,IWD,PBCT,WPX,EA,XLP,XLU,XLY,XLB,XLE,XLF,XLI,XLK,FOXA,PLUG,AKRX,FLEX,NFX,HCA,BLL,KBE,KBH,AMTD,USO,USB,RRC,AR,FEYE,FOX,VGK,BND,HAL,RIG,WU,DHR,INTC,ATVI,DB,DE,DD,DG,DO,STNG,VFC,CERN,UVXY,FSLR,AMD,HON,HOG,UGAZ,DISH,DNR,TER,NBL,NBR,JBLU,ACAD,DHI,PTN,SRPT,NVAX,ALLY,TGT,WMT,VZ,TWTR,ZNGA,CY,CF,CA,CL,SWN,SLCA,OAS,CYH,POT,TRIP,BBT,BBY,BBG,PVG,LNG,EXPR,ECA,PRU,V,ENDP,ABBV,ORCL,FEZ,UAA,LLY,EEM,BK,GSS,SGYP,PPL,IYR,CIT,CMCSA,QCOM,SIRI,SPLV,SPLS,IEMG,DUK,NUE,MUX,MUR,SYMC,OCN,RAI,RAD,EGO,HIG,TOL,BBBY,DUST,NXPI,WLL,AUY,AG,QVCA,GDXJ,KORS,NWL,PIR,CCJ,CCL,MS,FAS,TQQQ,ESRX,FITB,NFLX,AKAM,SRCI,GNTX,CSCO,BBRY,KSS,SFM,ZION,PGX,PGR,DYN,CAG,CAH,CAT,IBM,SM,SN,SO,SH,SU,FCX,VWO,HUN,TSO,TSN,JWN,YUM,LYB,EPI,OPK,SDS,AIG,GNC,WDC,GNW,PEG,COH,COF,COG,PEP,COP,DCTH,EMR,EMB,SYY,LVLT,CTSH,TVIX,DISCA,WFT,HZNP,WFC,WFM,SVXY,RH,RF,CELG,KOS,ERX,SBH,F,VNQ,CAR,BSX,SCHW,GLW,AKS,OKE,PCG,QQQ,EOG,TWX,XEL,VIAB,SLB,SLV,BKLN,CVE,CVS,CVX,SSRI,DLTR,ETN,KMI,MON,MOS,MEET,GSAT,AEO,AET,AES,AEP,OIH,JNUG,PAH,PAY,ETFC,RICE,VG,USMV,AMZN,PSEC,CTL,MAT,MAR,MAS,BWA,AGG,IJR,MACK,DAL,COMM,VOO,ICE,PSX,SBUX,ON,PM,PG,CRM,XLNX,DLPH,LQD,EXK,EXC,MCD,SLM,WPM,HOLX,AAL,ITB,UNH,UNG,UNP,XOM,NYCB,XOP,AMLP,JNPR,CPE,CPN,KGC,EZU,MET,GDX,GILD,BKD,HFC,AGN,ACN,NEE,IVZ,IVV,UPS,FE,HYG,XME,MCHP,CENX,NWSA,AXP,M,KEY,ADSK,FOLD,LUV,MGM,BMY,HDS,NGD,IPG,DKS,RSX,SSO,VEA,BRK.B,PTEN,MDRX,SPXU,SPXL,NG,NE,NI,LKQ,FLO,GXP,SVU,NAK,HBI,UTX,DIS,DIA,ZTS,SDRL,XIV,PNC,HBAN,LBTYK,LBTYA,ATW,ATI,YELP,OXY,CLVS,FNB,NEM,STX,STT,STI,BAC,BAX,CIEN,DOW,COST,MU,MO,MA,HLT,IEFA,AVP,MPC,NAVI,LOW,FHN,XRT,XRX,SABR,GPOR,SWKS,X,MDT,JNJ,APA,APC,MRK,MRO"; // "JNUG,JDST,NUGT,DUST";
